### ISSUE TITLE
Menu/links stop working when content fills last section in certain browsers.

### ISSUE THREAD

**Issue by dograbbit** [adtile/fixed-nav#18]
First of all thanks so much to adtile for uploading this, very cool code! This is my first time on GitHub - believe I'm seeing a bug but it could just be that I'm implementing something incorrectly.

I would like to have a footer that only shows up in the last section - one that goes all the way to the bottom of the screen. But when I place something at the bottom the menu and links stop working in Firefox and IE when you scroll to that area (on small screens the Menu toggle opens but the page does not scroll when you click on sections, likewise on large screens no scrolling when the header links are clicked). No issue in Chrome or on the mobile devices I've tried.

Here's the site I'm working on, scroll all the way to the bottom in Firefox/IE and the links stop working: http://viverolamilagrosa.tk/

I've been at it for hours but nothing I've come up with seems to help - the only way I can get the links to work is if I change the "top'' values in the below code raising the footer, but then I have an ugly gap between the footer and bottom of the page. 
/* grass box */
    .infoboxFooter {
        position:absolute;
        top: 3130px;
        left: 0;
        right: 0;
}

/* green fill and links box */
    .infoboxFooter2 {
        background-color: #516d18;
        position:absolute;
        top: 3280px;
        left: 0;
        right: 0;

I checked out the other questions but none seemed to match my problem. My apologies if this isn't how/where I should ask, very new to this. Thank you for looking at my issue - any ideas or guidance greatly appreciated!

**Comment by dograbbit** [comment]
Found a work-around!

**Comment by banbanbana** [comment]
What was the workaround you found @glunn?
