### ISSUE TITLE
Navigation text not aligning in center..

### ISSUE THREAD

**Issue by jshafiq** [adtile/fixed-nav#20]
can't seem to align the navigation text in center tried every option in the css file, any help would be appreciated. 
Thanks

**Comment by viljamis** [comment]
@jshafiq What navigation text do you mean? The links (home,about,etc), or something else?

**Comment by jshafiq** [comment]
Yes the navigation links, Can't seem to align them in center. @viljamis

**Comment by robhadfield** [comment]
Hey @jshafiq - something like this would work (if you're using the same html as the demo)

    .nav-collapse {
        width: 100%;
        float: none;
    }

    .nav-collapse ul {
        text-align: center;
    }

    .nav-collapse ul li {
        float: none;
        display: inline-block;
    }

That's just overriding the defaults in the inspector so tweak to suit :)

**Comment by jshafiq** [comment]
thanks @robhadfield made few changes to your code and got it working. ;)

**Comment by robhadfield** [comment]
Great stuff :+1: 

Good luck with your project.
