### ISSUE TITLE
Drop Down List

### ISSUE THREAD

**Issue by Jim1946** [adtile/fixed-nav#29]
Sorry about this - being new to programming and having been retired for a number of years I am impressed with the programme - but I cannot seem to add drop down programmes - could you please supply code for this

Thanks and Regards

**Comment by robhadfield** [comment]
Did you get it sorted @Jim1946 ?

**Comment by Jim1946** [comment]
No afraid not - I am new to Bootstrap, CSS and Html, I tried copying and pasting from another program - but this did not work - This is a super NavBar - Could you please help - Thanks

**Comment by robhadfield** [comment]
Hi Jim, we were all new to it once :)

If you go to the project home page ([https://github.com/adtile/fixed-nav](https://github.com/adtile/fixed-nav)) and click "Clone or Download" then download the zip file a working version is provided there.

Once downloaded, unzip the package and open the index.html file you will see a working menu and sliding page example. You can then either transfer your code into that page or copy over the required files to your project.

Hope that help
Rob
