### ISSUE TITLE
Remove #links on click

### ISSUE THREAD

**Issue by krowpac** [adtile/fixed-nav#31]
I'm just curious if there is an easy way to remove the hashtag-anchorlink from showing up in the URL?  The #home link does not show up and on scrolling there's no change to the URL, but if you click the other links then they show up in the menu bar.  For example: https://www.adtile.me/fixed-nav/#projects.

If anyone knows what I can change to remove this feature that would help me a lot as my knowledge of JS is shameful.  Thanks in advance!

**Comment by pgarciacamou** [comment]
The hashtag works as an "id finder", basically it will ask the browser to scroll down to the element that has the specified id in the hashtag, if there is NO hashtag, the fixed-nav will scroll to the top.
