### ISSUE TITLE
Outbound Links Break Section Highlighting

### ISSUE THREAD

**Issue by bartmc** [adtile/fixed-nav#33]
Hello!

I'm using the single-page-scrolling version of your plugin for my nav. It's working fine as long as all the nav links are for anchors in the page, but when I add an outbound link, I lose the section-highlighting for the in-page sections. The links and scrolling all still work, I just lose all of the section highlighting.

Any idea what I might be doing wrong? Thanks!

bart

**Comment by pgarciacamou** [comment]
Hey @bartmc could you add a bit of the code to help narrow it down? Thanks!

**Comment by bartmc** [comment]
This is the header and nav from the demo:

`<header>
      <a href="#home" class="logo" data-scroll>Fixed Nav</a>
      <nav class="nav-collapse">
        <ul>
          <li class="menu-item active"><a href="#home" data-scroll>Home</a></li>
          <li class="menu-item"><a href="#about" data-scroll>About</a></li>
          <li class="menu-item"><a href="#projects" data-scroll>Projects</a></li>
          <li class="menu-item"><a href="http://www.google.com" target="blank" data-scroll>Google</a></li>
        </ul>
      </nav>
    </header>`

The rest of the page and source files have not been changed.

bart

**Comment by pgarciacamou** [comment]
@bartmc I created PR #34 .. please test and let me know if everything works.

**Comment by bartmc** [comment]
Yes, that did it. Perfect! Thank you so much for your excellent work!

Bart McLaughlin
646-510-3342
bart@BartMcLaughlin.com

**Comment by pgarciacamou** [comment]
#34 merged
